---
exec_module: 'run_all_checks'

bilara_root_path: "${GITHUB_WORKSPACE}/root/pli/ms"
bilara_html_path: "${GITHUB_WORKSPACE}/html"
bilara_comment_path: "${GITHUB_WORKSPACE}/comment"
bilara_variant_path: "${GITHUB_WORKSPACE}/variant"
bilara_translation_path: "${GITHUB_WORKSPACE}/translation"
reference_root_path: "${GITHUB_WORKSPACE}/reference/pli/ms"

exclude_filepath: "${GITHUB_WORKSPACE}/.github/sc-renumber-segments-exclusion_file.yaml"

ms_yuttadhammo_path: ""
pali_concordance_filepath: ""
pali_canon_path: ""

# Based on the report file inside this dir exit status is determined, so keep the path valid
debug_dir: "${GITHUB_WORKSPACE}/report/"
# Error level. Print only thing that will show in report file
log_level: 40

